name: API CI
on:
  push:
    branches: [main]
    paths:
      - "backend/api/**"
      - ".github/workflows/api.yml"
      - ".github/workflows/service-ci.yml"
  pull_request:
    paths: ["backend/api/**"]
  workflow_dispatch: {} # permet un re-run manuel indépendant des filtres de chemin ci-dessus
jobs:
  ci:
    uses: ./.github/workflows/service-ci.yml
    permissions:
      contents: read
      packages: write
    with:
      service_path: backend/api
